### PR TITLE
Finished update for backend to accept an array of images!

### PR DESCRIPTION
**Pull request by MWeber313**
Co-authored-by: Dave Inden <davidinden@gmail.com>
Co-authored-by: Ian Schwartz <ian.schwartz23@gmail.com>
Co-authored-by: Grissobel Payonk <grissobel.castro@gmail.com>
Co-authored-by: Jason Loomis <jason@jrloomis.com>
Co-authored-by: Ami Scott <amiezrascott@gmail.com>

# Description

Backend can now accept an array of images

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Change Status

- [x] Complete, tested, ready to review and merge
- [ ] Complete, but not tested (may need new tests)
- [ ] Incomplete/work-in-progress, PR is for discussion/feedback

# How Has This Been Tested?

- Manually

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My code has been reviewed by at least one peer
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] There are no merge conflicts

### CODE REVIEW

**Review by daveskull81 — APPROVED** [review]
Saw this built out over zoom. Should be good to merge.

**Review by ian-schwartz — APPROVED** [review]
Witnessed on zoom, good to merge

**Review by grissobel — APPROVED** [review]
Saw most of it live, good to merge.

**Comment by daveskull81** [comment]
[Unable to add multiple photos](https://trello.com/c/9AcobXMs/101-unable-to-add-multiple-photos-on-mobile-for-web)

**Pull request merged**
